# Generated by Django 3.2.8 on 2021-10-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_type',
        ),
        migrations.AddField(
            model_name='medicine',
            name='PHARMACY',
            field=models.CharField(choices=[('Аптека', 'Нет в наличии'), ('Аптека', 'Алибегова ул., д. 13/1'), ('Аптека', 'Воронянского ул., д. 17а'), ('Аптека', 'Горецкого ул., д. 2'), ('Аптека', 'Городецкая ул., д. 30'), ('Аптека', 'Дзержинского пр-т, д. 119')], default='Нет в наличии', max_length=500),
        ),
        migrations.AddField(
            model_name='medicine',
            name='SUPPLIED_TYPE',
            field=models.CharField(choices=[('Не указано', 'Не указано'), ('Твердые', 'Таблетки'), ('Твердые', 'Порошок'), ('Твердые', 'Капсулы'), ('Твердые', 'Драже'), ('Твердые', 'Гранулы'), ('Мягкие', 'Мазь'), ('Мягкие', 'Крем'), ('Мягкие', 'Паста'), ('Мягкие', 'Гель'), ('Жидкие', 'Раствор'), ('Мягкие', 'Суспензия'), ('Мягкие', 'Капли'), ('Мягкие', 'Сироп'), ('Газообразные', 'Аэрозоль')], default='Не указано', max_length=100),
        ),
    ]
