# Generated by Django 3.2.8 on 2021-10-23 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20211014_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='PHARMACY',
            field=models.CharField(choices=[('Нет в наличии', 'Нет в наличии'), ('Алибегова ул., д. 13/1', 'Алибегова ул., д. 13/1'), ('Воронянского ул., д. 17а', 'Воронянского ул., д. 17а'), ('Горецкого ул., д. 2', 'Горецкого ул., д. 2'), ('Городецкая ул., д. 30', 'Городецкая ул., д. 30'), ('Дзержинского пр-т, д. 119', 'Дзержинского пр-т, д. 119')], default='Нет в наличии', max_length=500),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='SUPPLIED_TYPE',
            field=models.CharField(choices=[('Не указано', 'Не указано'), ('Таблетки', 'Таблетки'), ('Порошок', 'Порошок'), ('Капсулы', 'Капсулы'), ('Драже', 'Драже'), ('Гранулы', 'Гранулы'), ('Мазь', 'Мазь'), ('Крем', 'Крем'), ('Паста', 'Паста'), ('Гель', 'Гель'), ('Раствор', 'Раствор'), ('Суспензия', 'Суспензия'), ('Капли', 'Капли'), ('Сироп', 'Сироп'), ('Аэрозоль', 'Аэрозоль'), ('Другое', 'Другое')], default='Не указано', max_length=100),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, upload_to='user/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
